name: Gummi CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install dependencies
      run: sudo apt install intltool libglib2.0-dev libgtk-3-dev libgtksourceview-3.0-dev libpoppler-glib-dev libgtkspell3-3-dev libsynctex-dev -y
    - name: autogen
      run: ./autogen.sh
    - name: configure
      run: ./configure
    - name: make
      run: make
